# Generated by Django 3.2.9 on 2022-06-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktask',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
