# Generated by Django 3.2.9 on 2022-06-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booklist', '0004_booktask_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktask',
            name='book',
        ),
    ]
