# Generated by Django 3.2.9 on 2022-06-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booklist', '0005_remove_booktask_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktask',
            name='book',
            field=models.FileField(null=True, upload_to='book'),
        ),
    ]
